<?php
$url = array(
"https://i.postimg.cc/Mc7rWvFv/12334wrwd534wrdf-1.gif",
"https://i.postimg.cc/R3LGk2Wt/12334wrwd534wrdf-2.gif",
"https://i.postimg.cc/CRj489H2/12334wrwd534wrdf-3.gif",
"https://i.postimg.cc/MMr0xwqn/12334wrwd534wrdf-4.gif",
"https://i.postimg.cc/KK2Jsm8F/12334wrwd534wrdf-5.gif",
"https://i.postimg.cc/dZLBT14R/12334wrwd534wrdf-6.gif",
"https://i.postimg.cc/Fd1cT63N/12334wrwd534wrdf-7.gif",
"https://i.postimg.cc/rKRjVDdM/12334wrwd534wrdf-8.gif",
"https://i.postimg.cc/G2fsCYtS/anime-slap.gif",
"https://i.postimg.cc/C5fnL1fM/slap-anime.gif",
"https://i.postimg.cc/ydxStn1Z/VW0cOyL.gif", "https://i.pinimg.com/originals/49/fe/91/49fe91d5ee9827b8400b8a30c55b6323.gif",
"https://i.pinimg.com/originals/23/bb/67/23bb67307050fc87d5f88cd480286c97.gif",
"https://i.pinimg.com/originals/49/de/17/49de17c6f21172b3abfaf5972fddf6d6.gif",
"https://i.pinimg.com/originals/61/72/5a/61725a5da1421168c3c1331925f80e2a.gif",
"https://i.imgur.com/VW0cOyL.gif",
"https://i.imgur.com/GPQJEx5.gif",
"https://i.imgur.com/7ZuxSvs.gif",
"https://i.imgur.com/mdZR2D2.gif",
"https://i.imgur.com/ABE1arT.gif",
"https://i.imgur.com/Li9mx3A.gif",
"https://i.imgur.com/kVI9SHf.gif",
"https://i.imgur.com/8r0MdsM.gif",
"https://i.imgur.com/bmYgtPk.png",
"https://i.imgur.com/QMh9KWv.gif",
"https://i.imgur.com/d2G5kLo.gif",
"https://i.imgur.com/sKDLYXE.gif",
"https://i.imgur.com/FQKJpzU.gif",
"https://i.imgur.com/3ultMVh.gif",
"https://i.imgur.com/miFmhBg.gif",
"https://i.imgur.com/GsLRT0o.gif",
"https://i.imgur.com/ISDUslk.gif",
"https://i.imgur.com/Q6iX9OA.gif",
"https://i.imgur.com/XqtlhuZ.gif",
"https://i.imgur.com/0B7O5Zi.gif",
"https://i.imgur.com/28BGRwI.gif",
"https://i.imgur.com/HcTCdJ1.gif",
"https://i.imgur.com/HqHljrw.gif",
"https://i.imgur.com/yAlP0u1.gif",
"https://i.imgur.com/xxLRyua.gif",
"https://i.imgur.com/CfKJ1qV.gif",
"https://i.imgur.com/pDUJHZX.gif",
"https://i.imgur.com/ESD4TJ2.gif",
"https://i.imgur.com/ZDiDDdc.gif",
"https://i.imgur.com/xylnYFw.gif",
"https://i.imgur.com/YKc7b5Q.gif",
"https://i.imgur.com/tRq8aRL.gif",
"https://i.imgur.com/MnOXs78.gif",
"https://i.imgur.com/jArgSfw.gif",
"https://i.imgur.com/dKPoLH6.gif",
"https://i.imgur.com/7GMClk3.gif",
"https://i.imgur.com/Er0tNFE.gif",
"https://i.imgur.com/GQIGGII.gif",
"https://i.imgur.com/sVeYncu.gif",
"https://i.imgur.com/90Bgbao.gif",
"https://i.imgur.com/w66ZqGR.gif",
"https://i.imgur.com/nuDmQu5.gif",
"https://i.imgur.com/wlLCjRo.gif",
"https://i.imgur.com/2pUiMqj.gif",
"https://i.imgur.com/h9VNMim.gif",
"https://i.imgur.com/FWIdKzK.gif",
"https://i.imgur.com/n6sJHYY.gif",
"https://i.imgur.com/noP8nqB.gif",
"https://i.imgur.com/EhJ5aZ0.gif",
"https://i.imgur.com/3t2xNmE.gif",
"https://i.imgur.com/ySSXe1l.gif",
"https://i.imgur.com/8gpUKMc.gif",
"https://i.imgur.com/81dy6O6.gif",
"https://i.imgur.com/HFg7Gdm.gif",
"https://i.imgur.com/YyAtcXP.gif",
"https://i.imgur.com/hpc7zcj.gif",
"https://i.imgur.com/luv7WOg.gif",
"https://i.imgur.com/ynLi8NU.gif",
"https://i.imgur.com/weNCfYA.gif",
"https://i.imgur.com/5AamjO0.gif",
"https://i.imgur.com/8hsSb0i.gif",
"https://i.imgur.com/o1n107h.gif",
"https://i.imgur.com/i4JpIfd.gif",
"https://i.imgur.com/hvU4fCG.gif",
"https://i.imgur.com/bwCDVka.gif",
"https://i.imgur.com/Xrp1ZGx.gif",
"https://i.imgur.com/2uDXNDh.gif",
"https://i.imgur.com/eRDDdpf.gif",
"https://i.imgur.com/SJfYgVn.gif",
);
$x2 = array_rand($url);
$x2vip = $url [$x2];
$trai = array(
"data" => $x2vip,
"author" => "X2",
"success" => "true",
);
$rdimg = json_encode($trai);

$i = ['\/v\/','\/','X2 IS HERE'];
$t = ['/v/','/','X2 IS HERE'];
$j = str_replace($i, $t, $rdimg);
echo $j;